site_name: Programmation Fonctionnelle - OCaml - Polytech Saclay
# site_url: "https://ocaml.durier.xyz/fr/"


nav:
  - Accueil: 
    - index.md
    - Fonctionnement du cours: 
        - home/index.md
        - 🌐Moodle (devoirs/questions): 'https://moodle.durier.xyz'
        - 🌐Plateforme learn-ocaml: 'https://learn-ocaml.durier.xyz'
    - Ressources en ligne: 
        - resources/index.md
        - Utiliser OCaml: resources/install.md
        - Cours, supports de cours et exercices en ligne: resources/courses.md
  - Transparents: 
    - slides/index.md
    - Cours 1 - Introduction à OCaml: slides/1.1-intro.md
    - Cours 1 - Typage et Expressions: slides/1.2-types.md
#  - Glossaire: /glossary/index.md
  - A propos: 
    - about/index.md
    - Licence: about/license.md
#    - Sources: about/sources.md
#    - Outils: about/tools.md
not_in_nav: |
  /wip.md


theme:
    name: 'material'
    features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.expand # "the left sidebar will expand all collapsible subsections by default"
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
#    - toc.integrate
    logo: ../assets/logo.png
    icon:
      repo: fontawesome/brands/git-alt


    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

# Extensions
markdown_extensions:
  - nl2br
  - footnotes
  - admonition
  - abbr
  - md_in_html
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
#  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

      
repo_url: https://github.com/adurier/ocaml-course
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/adurier
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Français
      link: /fr/
      lang: fr
plugins:
  - search
  - obsidian-bridge
  - callouts
  - projects

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
