nav:
  - Accueil: index.md
  - Transparents: 
    - slides/index.md
    - Cours 1 - Introduction à OCaml: slides/1.1-intro.md
    - Cours 1 - Typage et Expressions: slides/1.2-types.md
  - Publications: 'publis.md'
  - A propos: about.md